language: ruby
bundler_args: --no-deployment
before_install:
- gem update --system 2.0.14
- gem --version
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
deploy:
  provider: rubygems
  api_key:
    secure: Zu4e5eS5MQiQgAa3VKG9w+lv8dxrcWSvOge6jFaWviVgZhHf8dN2BFO6PvZ4RcR4rfy216DBmouFWte/PqvsTpcrkuRs3EYNpXiMLrd9zvEG6UxewT76xcxhlSUSO37y6hLz5uZKCOEasdGrEkyt2bAqJZQnfhHKhHAewKRp9Jc=
#  gem: rubygems_allow-pre-releases
#  on:
#    repo: zebardy/rubygems_allow-pre-releases
